# Server
server.port=8080

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/rwms_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root74*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=floZKUOP4IRyU0vsdw3T9BiPSpwfDm4KnzP+kWtz0I8=
jwt.expiration=32400000
